### PR TITLE
Support new CLIP models (back to old install)

### PR DESCRIPTION
**Pull request by afiaka87**
Wasn't expecting an update from openai so soon but I think we have to do this (unfortunately) again until rom1504's branch for the `clip-anytorch` package is even with main.

### CODE REVIEW

**Comment by afiaka87** [comment]
https://github.com/rom1504/CLIP/pull/1

I made a PR for it but i'm not sure if @rom1504 wants the extra burden; so no pressure to them if that's the case.

**Comment by afiaka87** [comment]
Just added a fix for non-distributed.

**Comment by mehdidc** [comment]
Thanks a lot @afiaka87  for all the changes! looks good

**Comment by rom1504** [comment]
@afiaka87 I merged your pr and released https://pypi.org/project/clip-anytorch/

now that I see they merge PRs I'm wondering whether I should contribute back the change in torch dependency and even the .github/workflows for pip packaging though. Not sure if they'd accept it

**Pull request merged**
